# run the playbook with -K (capital) to ask the password
---
- name: Set Docker socket permission
  hosts: docker-host
  gather_facts: false
  vars_files:
  - environment.yml
  user: "{{env_vars.USER}}"
  become: true
  become_user: "{{env_vars.USER}}"
  tasks:
  - name: create new docker group 
    ansible.builtin.group:
      name: docker
      state: present
  - name: Add user to docker group
    ansible.builtin.user:
      name: venu
      groups: docker
      append: true
  - name: Reset ssh connection to allow user changes to affect ansible user
    ansible.builtin.meta:
      reset_connection
  - name: printing message for user
    debug:
      msg: "{{author_msg.msg1}}"