- name: Install packages for kubernetes
  hosts: all
  become: true
  become_user: root
  user: '{{USER}}'
  vars_files:
  - env.yml
  tasks:
  - name: run apt update command
    apt:
      update_cache: true
      update_cache_retries: 2
      update_cache_retry_max_delay: 5
      upgrade: true #use it when required

    tags: apt-update
