---
- name: Initialize kubeadm cluster and join worker nodes
  hosts: master
  become: true
  user: '{{USER}}'
  vars_files:
    - env.yml
  vars:
    user_home: "/home/{{ ansible_user }}"
  tasks:
    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command to local file
      local_action:
        module: copy
        content: "{{ join_command.stdout }}"
        dest: "./join-command"

- name: Join worker nodes to the cluster
  hosts: worker
  become: true
  tasks:
    - name: Copy the join command to server location
      copy: 
        src: "./join-command"
        dest: "/tmp/join-command.sh"
        mode: '0777'

    - name: Join the node to the cluster
      command: sh /tmp/join-command.sh
