- name: Create User and Groups for new users
  hosts: all
  become: true
  vars_files:
    - user_var.yml
  tasks:
    - name: Create group
      group:
        name: "{{ item }}"
        state: present
      loop: "{{ new_user }}"
      tags:
        - group

    - name: Create Users Task
      user:
        name: "{{ item }}"
        state: present
        password: "{{ default_user_password | password_hash('sha512','A512') }}"
        shell: /bin/bash
        group: "{{item}}"
        groups: sudo
      loop: "{{ new_user }}"
      tags:
        - user