# run the playbook with -K (capital) to ask the password
---
- name: Install docker
  hosts: docker-host
  vars_files:
  - environment.yml
  user: "{{env_vars.USER}}"
  tasks:
  - name: Download the docker install script from internet
    command: curl -fsSL https://get.docker.com -o get-docker.sh
    become: true
    # become_user: venu
    become_method: sudo
  - name: execute the downloaded script to install docker
    command: sh get-docker.sh
    become: true
    # become_user: venu
    become_method: sudo
    - name: printing message for user
    debug:
      msg: "{{author_msg.msg1}}"